name: Build native libs
on:
  workflow_dispatch:
    inputs:
      sdl-tag:
        description: "The SDL release tag to build"
        required: true
        type: string

jobs:
  build:
    name: Build SDL for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, windows-11-arm, macos-13, macos-latest]

    steps:
      - name: Setup SDL
        uses: libsdl-org/setup-sdl@main
        id: sdl-setup
        with:
          install-linux-dependencies: true
          version: 3-latest
          version-sdl-image: 3-latest
          version-sdl-mixer: 3-latest
          version-sdl-ttf: 3-latest

      - name: Prepare CMake
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build SDL ${{ steps.sdl-setup.outputs.version }}
        run: cmake --build build --config Release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SDL-${{ steps.sdl-setup.outputs.version }}-${{ matrix.os }}
          path: build
