name: YDMS Release Builds

on:
  release:
    types:
      - published

jobs:
  build-publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: ['SDL3-CS/SDL3-CS.sln' ,'SDL3-CS.Native/SDL3-CS.Native.sln']

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Build & Pack
        run: |
          dotnet build -c Release ${{ matrix.project }} -p:Version=${{ github.event.release.tag_name }}
          dotnet pack -c Release ${{ matrix.project }} -p:Version=${{ github.event.release.tag_name }}

      - name: Publish to NuGet
        run: |
          dotnet nuget push **/*.nupkg -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json
